// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalvWKxD4OHJ44g_8hLcQpyBGSrJ_f8lA',
    appId: '1:369062827583:web:b627611e9e940dd0ba0a8a',
    messagingSenderId: '369062827583',
    projectId: 'simpleproductapp-937a3',
    authDomain: 'simpleproductapp-937a3.firebaseapp.com',
    storageBucket: 'simpleproductapp-937a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEVbNbb7t7qA9oInaodHLB3BQABQSI04',
    appId: '1:369062827583:android:e25b7153167640ffba0a8a',
    messagingSenderId: '369062827583',
    projectId: 'simpleproductapp-937a3',
    storageBucket: 'simpleproductapp-937a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_y-TSiKBzoWkt0VAkn98QEYBkTexFl8w',
    appId: '1:369062827583:ios:f9c95ea9689b2e00ba0a8a',
    messagingSenderId: '369062827583',
    projectId: 'simpleproductapp-937a3',
    storageBucket: 'simpleproductapp-937a3.firebasestorage.app',
    iosBundleId: 'com.example.simpleProductApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_y-TSiKBzoWkt0VAkn98QEYBkTexFl8w',
    appId: '1:369062827583:ios:f9c95ea9689b2e00ba0a8a',
    messagingSenderId: '369062827583',
    projectId: 'simpleproductapp-937a3',
    storageBucket: 'simpleproductapp-937a3.firebasestorage.app',
    iosBundleId: 'com.example.simpleProductApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCalvWKxD4OHJ44g_8hLcQpyBGSrJ_f8lA',
    appId: '1:369062827583:web:f86cb8c625c709cdba0a8a',
    messagingSenderId: '369062827583',
    projectId: 'simpleproductapp-937a3',
    authDomain: 'simpleproductapp-937a3.firebaseapp.com',
    storageBucket: 'simpleproductapp-937a3.firebasestorage.app',
  );
}
